publish:
	./gradlew --no-daemon publishAggregationToCentralPortal
publish-snap:
	./gradlew --no-daemon -PprojectVersion=0.0.3-SNAPSHOT publishAggregationToCentralSnapshots
publish-local:
	./gradlew --no-daemon publishToMavenLocal
